# Site settings
title: Itinero
description: 'Open source routing engine for .NET'
url: 'http://www.itinero.tech/' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Itinero'
  email: ben@itinero.tech
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  itinero
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
